Added gradle s3 plugin

diff --git a/bin/airpal b/bin/airpal
--- a/bin/airpal
+++ b/bin/airpal
@@ -2,15 +2,19 @@
 
 # Wrapper for Airpal Server
 
-AIRPAL_HOME=/usr/share/airpal
+AIRPAL_HOME=/usr/lib/airpal
 LOGFILE=$AIRPAL_HOME/server.log
 PIDFILE=$AIRPAL_HOME/server.pid
 
 case "$1" in
 	start)
 		java -server -Duser.timezone=UTC -cp $AIRPAL_HOME/airpal.jar com.airbnb.airpal.AirpalApplication server $AIRPAL_HOME/reference.yml 2>&1 >> $LOGFILE &
-		echo $! > $PIDFILE
-		echo "Start [OK]"
+		if [ $? -eq 0 ]; then
+			echo $! > $PIDFILE
+			echo "Start [OK]"
+		else
+			echo "Start [FAIL]"
+		fi
 		$0 status
 		;;
 	stop)
